# This is the mods.toml file. It contains the metadata for your mod.
# The file format is TOML. For more information, see https://github.com/toml-lang/toml

# Mandatory display name for your mod. This is the name that will be shown to the user.
modLoader="javafml"

# Mandatory loader version specification. This specifies the version range of the loader that your mod requires.
# The recommended range for 1.20.1 is [47,).
loaderVersion="[47,)"

# Mandatory license specification for your mod. This is the license under which your mod is distributed.
license="All Rights Reserved" # Example: "MIT", "GPLv3", "All Rights Reserved"

# A list of mods - Mandatory
[[mods]]
# Mandatory mod ID for your mod. This is the unique identifier for your mod.
modId="yourmodid"

# Mandatory version specification for your mod. This is the version of your mod.
# It is recommended to use the ${file.jarVersion} variable, which is automatically replaced by Gradle.
version="${file.jarVersion}"

# Mandatory display name for your mod. This is the name that will be shown to the user.
displayName="Your Mod Name"

# Optional URL to your mod's update checker JSON file. This allows Forge to check for updates for your mod.
# updateJSONURL="https://change.me.to.your.update.json.example.invalid/"

# Optional URL to your mod's homepage. This is the URL that will be opened when the user clicks on your mod in the mod list.
# displayURL="https://change.me.to.your.mods.homepage.example.invalid/"

# Optional path to your mod's logo file. This is the logo that will be shown in the mod list.
# logoFile="yourmodid_logo.png"

# Optional credits specification for your mod. This is where you can thank people who helped you create your mod.
# credits="Thanks for this example mod goes to Java"

# Optional authors specification for your mod. This is the list of authors who created your mod.
authors="Your Name"

# Mandatory description for your mod. This is the description that will be shown to the user.
# It can be multi-line by using triple single quotes.
description=\'\'\'A brief description of your mod.
Use newlines for longer descriptions.\'\'\'

# A list of dependencies for your mod - Optional
[[dependencies.yourmodid]] # The modId of the mod you depend on
    modId="forge" # Mandatory
    mandatory=true # Mandatory
    # The version range of the dependency. Recommended range for 1.20.1 is [47,)
    versionRange="[47,)" # Mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.yourmodid]]
    modId="minecraft" # Mandatory
    mandatory=true
    # The version range of the dependency. Recommended range for 1.20.1 is [1.20.1,1.21)
    versionRange="[1.20.1,1.21)" # Mandatory
    ordering="NONE"
    side="BOTH"

